const { getUnsplashImages } = require("../data/api");
const {
    getUserPostedImages,
    getBinnedImages,
    updateImage,
    isImagePostBinned,
    deletePostedImage,
    uploadImagePost,
    getMostPopularImages,
} = require("../data/redis-db");

const data = [
    {
        id: "H0bmuj6xCN4",
        url: "https://images.unsplash.com/photo-1648737966762-1c8921f9b976?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MXwxfGFsbHwxfHx8fHx8Mnx8MTY0OTY4NTk2Mw&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Surface",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 11,
        __typename: "ImagePost",
    },
    {
        id: "8Rv4mGhAcSk",
        url: "https://images.unsplash.com/photo-1649624566474-bf5c94b36a40?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwyfHx8fHx8Mnx8MTY0OTY4NTk2Mw&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Pawel Czerwinski",
        description: "3D render (Blender 3.1)",
        userPosted: false,
        binned: false,
        numBinned: 5,
        __typename: "ImagePost",
    },
    {
        id: "MfJzTNcr0Wo",
        url: "https://images.unsplash.com/photo-1500175276127-8c7c0c499036?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwzfHx8fHx8Mnx8MTY0OTY4NTk2Mw&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Nathan Anderson",
        description: "woman surrounded sunflowers",
        userPosted: false,
        binned: false,
        numBinned: 44,
        __typename: "ImagePost",
    },
    {
        id: "2Mpm744F9WE",
        url: "https://images.unsplash.com/photo-1649658029205-842ec48e6632?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHw0fHx8fHx8Mnx8MTY0OTY4NTk2Mw&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Trae Gould",
        description: "The Underworld ",
        userPosted: false,
        binned: false,
        numBinned: 4,
        __typename: "ImagePost",
    },
    {
        id: "MvPerK2jVUY",
        url: "https://images.unsplash.com/photo-1649644712561-958371019e23?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHw1fHx8fHx8Mnx8MTY0OTY4NTk2Mw&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Susan Wilkinson",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 2,
        __typename: "ImagePost",
    },
    {
        id: "8kqtv6dMNSg",
        url: "https://images.unsplash.com/photo-1648737154448-ccf0cafae1c2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MXwxfGFsbHw2fHx8fHx8Mnx8MTY0OTY4NTk2Mw&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Windows",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 46,
        __typename: "ImagePost",
    },
    {
        id: "KFA4mrgGVDQ",
        url: "https://images.unsplash.com/photo-1649623903858-200368a04420?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHw3fHx8fHx8Mnx8MTY0OTY4NTk2Mw&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Luke Thornton",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 5,
        __typename: "ImagePost",
    },
    {
        id: "BB0PUkzFejk",
        url: "https://images.unsplash.com/photo-1649616581787-5135b95974d0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHw4fHx8fHx8Mnx8MTY0OTY4NTk2Mw&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Anastasiya Leskova",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 5,
        __typename: "ImagePost",
    },
    {
        id: "oL6DEqRG2z8",
        url: "https://images.unsplash.com/photo-1649659461524-fa4a3dd9106e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHw5fHx8fHx8Mnx8MTY0OTY4NTk2Mw&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Julia Koi",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 4,
        __typename: "ImagePost",
    },
    {
        id: "VcKCPQUDVcM",
        url: "https://images.unsplash.com/photo-1649636269015-d92f1f08f11d?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwxMHx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "zero take",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 6,
        __typename: "ImagePost",
    },
    {
        id: "0VEDrQXxrQo",
        url: "https://images.unsplash.com/photo-1553272725-086100aecf5e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MXwxfGFsbHwxMXx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Collins Lesulie",
        description: "man using laptop inside room",
        userPosted: false,
        binned: false,
        numBinned: 1635,
        __typename: "ImagePost",
    },
    {
        id: "3BxoPmF6o48",
        url: "https://images.unsplash.com/photo-1649672460521-4afb57c363f3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwxMnx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Documerica",
        description:
            "May 1974: Two men, Chicago’s South Side (John H. White / Documerica)",
        userPosted: false,
        binned: false,
        numBinned: 3,
        __typename: "ImagePost",
    },
    {
        id: "VevVvLjfmy4",
        url: "https://images.unsplash.com/photo-1649605475361-d8cf71dd69ea?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwxM3x8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Mitchell Luo",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 9,
        __typename: "ImagePost",
    },
    {
        id: "nfi-TXXzwjI",
        url: "https://images.unsplash.com/photo-1649605184337-c4dc52c6e32e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwxNHx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Parsa Mahmoudi",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 12,
        __typename: "ImagePost",
    },
    {
        id: "wakpYokUd7Y",
        url: "https://images.unsplash.com/photo-1649633835836-dd45bbdfbdac?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwxNXx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Marlon Schmeiski",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 5,
        __typename: "ImagePost",
    },
    {
        id: "lFmuWU0tv4M",
        url: "https://images.unsplash.com/photo-1536329583941-14287ec6fc4e?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MXwxfGFsbHwxNnx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Keila Hötzel",
        description: "White page with color chart for your ideas!",
        userPosted: false,
        binned: false,
        numBinned: 3008,
        __typename: "ImagePost",
    },
    {
        id: "rIb4ykHGxvA",
        url: "https://images.unsplash.com/photo-1649598090984-ed21c7e53b1c?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwxN3x8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Manda Hansen",
        description:
            "Desert sunrise at the Cholla Cactus Garden in Joshua Tree National Park (California). \n\nI'd love to see how you use this photo! Tag me on social media @mandacreatespretty. ",
        userPosted: false,
        binned: false,
        numBinned: 13,
        __typename: "ImagePost",
    },
    {
        id: "Ik3HekygRoY",
        url: "https://images.unsplash.com/photo-1649669640707-cb447a8ab295?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwxOHx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Albina White",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 14,
        __typename: "ImagePost",
    },
    {
        id: "lZX0GclwjT4",
        url: "https://images.unsplash.com/photo-1649649853889-48bf9f53dcd0?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwxOXx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Anand Karthikeyan",
        description: "red panda view",
        userPosted: false,
        binned: false,
        numBinned: 11,
        __typename: "ImagePost",
    },
    {
        id: "5fCNKRCbx58",
        url: "https://images.unsplash.com/photo-1646835962680-19b0244c4741?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwyMHx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Laura Kennedy",
        description: "Roam North clothing and provisions t-shirt ",
        userPosted: false,
        binned: false,
        numBinned: 5,
        __typename: "ImagePost",
    },
    {
        id: "3EnlBPEgIxM",
        url: "https://images.unsplash.com/photo-1648737965402-2b9c3f3eaa6f?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MXwxfGFsbHwyMXx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Surface",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 15,
        __typename: "ImagePost",
    },
    {
        id: "dB7WF2Hlfkw",
        url: "https://images.unsplash.com/photo-1649673755195-cba28495c86b?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwyMnx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "eberhard 🖐 grossgasteiger",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 9,
        __typename: "ImagePost",
    },
    {
        id: "AWxdK9s4pW8",
        url: "https://images.unsplash.com/photo-1649668794619-4dd0821d86c2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwyM3x8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Mikhail Volkov",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 11,
        __typename: "ImagePost",
    },
    {
        id: "JHNPqGKR9II",
        url: "https://images.unsplash.com/photo-1649615644662-5f33602a08c2?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwyNHx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Silvia",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 5,
        __typename: "ImagePost",
    },
    {
        id: "7smLV8cCWdc",
        url: "https://images.unsplash.com/photo-1649647461896-6c5620fb1ec6?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwyNXx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Dynamic Wang",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 6,
        __typename: "ImagePost",
    },
    {
        id: "Y2ravKRtQZ0",
        url: "https://images.unsplash.com/photo-1648737153811-69a6d8c528bf?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MXwxfGFsbHwyNnx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Windows",
        description: null,
        userPosted: false,
        binned: true,
        numBinned: 40,
        __typename: "ImagePost",
    },
    {
        id: "JD6czWal51w",
        url: "https://images.unsplash.com/photo-1649675207604-55f5857da6b3?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwyN3x8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Malik Skydsgaard",
        description: "Down the road",
        userPosted: false,
        binned: false,
        numBinned: 11,
        __typename: "ImagePost",
    },
    {
        id: "QBdg4dTz1MU",
        url: "https://images.unsplash.com/photo-1649646861819-47c248aca8d4?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwyOHx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Alexey Demidov",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 9,
        __typename: "ImagePost",
    },
    {
        id: "tERhSdEewCk",
        url: "https://images.unsplash.com/photo-1649675603179-ef3d38142ba8?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwyOXx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "DDP",
        description: "flowers on a pot and a mirror laying along a white wall",
        userPosted: false,
        binned: false,
        numBinned: 6,
        __typename: "ImagePost",
    },
    {
        id: "vww9tCx562I",
        url: "https://images.unsplash.com/photo-1649632964585-2ab3a295c173?crop=entropy&cs=tinysrgb&fit=max&fm=jpg&ixid=MnwzMTU4NDh8MHwxfGFsbHwzMHx8fHx8fDJ8fDE2NDk2ODU5NjM&ixlib=rb-1.2.1&q=80&w=1080",
        posterName: "Anton Ponomarenko",
        description: null,
        userPosted: false,
        binned: false,
        numBinned: 9,
        __typename: "ImagePost",
    },
];

const resolvers = {
    Query: {
        unsplashImages: async (_, { pageNum = 0 }) => {
            return data;
            const unsplashImages = await getUnsplashImages(pageNum);
            return unsplashImages;
        },
        binnedImages: async () => {
            const binnedImages = await getBinnedImages();
            return binnedImages;
        },
        userPostedImages: async () => {
            const postedImages = await getUserPostedImages();
            return postedImages;
        },
        getTopTenBinnedPosts: async () => {
            const mostPopular = await getMostPopularImages();
            return mostPopular;
        },
    },
    ImagePost: {
        binned: async (parentValue) => {
            return await isImagePostBinned(parentValue.id);
        },
    },
    Mutation: {
        updateImage: async (
            _,
            { id, url, posterName, description, userPosted, binned, numBinned }
        ) => {
            await updateImage({
                id,
                url,
                posterName,
                description,
                userPosted,
                binned,
                numBinned,
            });
            return {
                id,
                url,
                posterName,
                description,
                userPosted,
                binned,
                numBinned,
            };
        },
        deleteImage: async (_, { id }) => {
            await deletePostedImage(id);
            return null;
        },
        uploadImage: async (_, { url, description, posterName }) => {
            return await uploadImagePost({ url, description, posterName });
        },
    },
};

module.exports = { resolvers };
